# Swagger 설정
springdoc:
  version: 1.0.0
  packages-to-scan: jongho.blog
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: text/plain;charset=UTF-8
  default-produces-media-type: text/plain;charset=UTF-8